package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/kohmebot/kohme/pkg/conf"
	"golang.org/x/mod/semver"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"os/signal"
	"path"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

const template = `
// Code generated by plugin_gen; DO NOT EDIT.
package main

%s

func init()  {
	%s
}

`

const genPath = "./cmd/bot/plugin.gen.go"
const schemaPath = "./cmd/schemas_gen/plugin.gen.go"
const readmeName = "README.md"
const readmeAssertPath = "docs"
const pluginDocPath = "./.docs/docs"

func main() {

	pluginConf := conf.PluginConf{}

	err := pluginConf.ParseYamlFile(conf.PluginConfigPath)
	if os.IsNotExist(err) {
		_ = conf.CreatePluginConf()
		err = pluginConf.ParseYamlFile(conf.PluginConfigPath)
	}

	if err != nil {
		panic(err)
	}

	var recoverFile func()

	if b, ok := bak(); ok {
		recoverFile = func() {
			_ = writePlugin(b)
		}
	} else {
		recoverFile = func() {
			_ = os.Remove(genPath)
		}
	}

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sigs
		recoverFile()
		os.Exit(1)
	}()

	time.Sleep(500 * time.Millisecond)

	if err := gen(pluginConf.Plugins); err != nil {
		recoverFile()
		panic(err)
	}

}

func gen(plugins conf.PluginConfMap) error {
	var (
		importBuilder strings.Builder
		newBuilder    strings.Builder
		getUrl        []string
		urlMap        = map[string]string{}
	)

	for name, c := range plugins {
		if len(c.Repo) <= 0 {
			c.Repo = fmt.Sprintf("github.com/kohmebot/%s", name)
		}
		name = path.Base(c.Repo)
		if name == "core" {
			continue
		}

		if semver.Compare(c.Version, "v2.0.0") >= 0 {
			// v2或以上版本
			major := semver.Major(c.Version)
			_, last := path.Split(c.Repo)
			if last != major {
				c.Repo = path.Join(c.Repo, major)
			}
		}
		importBuilder.WriteString(fmt.Sprintf(`import "%s"`, path.Join(c.Repo, name)))
		importBuilder.WriteByte('\n')
		newBuilder.WriteString(fmt.Sprintf("reg.RegisterAny(%s.NewPlugin)\n", name))

		var u string
		if len(c.Version) <= 0 {
			u = fmt.Sprintf("%s@latest", c.Repo)
		} else {
			u = fmt.Sprintf("%s@%s", c.Repo, c.Version)
		}
		getUrl = append(getUrl, u)
		urlMap[u] = name

	}

	if len(getUrl) > 0 {
		importBuilder.WriteString(`import "github.com/kohmebot/kohme/pkg/reg"`)
		importBuilder.WriteByte('\n')
	}

	p := fmt.Sprintf(template, importBuilder.String(), newBuilder.String())

	if err := writePlugin([]byte(p)); err != nil {
		return err
	}

	for _, u := range getUrl {
		if err := getMod(u); err != nil {
			return err
		}
	}

	for _, u := range getUrl {
		dir, err := getModDir(u)
		if err != nil {
			return err
		}
		err = copyDoc(urlMap[u], dir)
		if err != nil {
			return err
		}
	}

	return copyFile(genPath, schemaPath)
}

func bak() ([]byte, bool) {
	if _, err := os.Stat(genPath); err != nil {
		return nil, false
	}

	b, err := os.ReadFile(genPath)
	if err != nil {
		return nil, false
	}

	return b, true

}

func writePlugin(b []byte) error {
	file, err := os.Create(genPath)
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = file.Write(b)
	return err
}

func getMod(url string) error {
	cmd := exec.Command("go", "get", url)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

func getModDir(url string) (string, error) {
	cmd := exec.Command("go", "list", "-m", "-json", url)
	var out bytes.Buffer
	cmd.Stdout = &out
	err := cmd.Run()
	if err != nil {
		return "", err
	}
	var mp map[string]any
	err = json.Unmarshal(out.Bytes(), &mp)
	if err != nil {
		return "", err
	}
	dir := mp["Dir"].(string)
	return dir, nil
}

func copyDoc(name string, modPath string) error {
	destDir := filepath.Join(pluginDocPath, name)
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return fmt.Errorf("create dest dir: %w", err)
	}

	entries, err := os.ReadDir(modPath)
	if err != nil {
		return fmt.Errorf("read mod dir: %w", err)
	}

	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if strings.EqualFold(e.Name(), readmeName) {
			if err := copyFile(
				filepath.Join(modPath, e.Name()),
				filepath.Join(destDir, readmeName),
			); err != nil {
				return fmt.Errorf("copy readme: %w", err)
			}
			break
		}
	}

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if strings.EqualFold(e.Name(), readmeAssertPath) {
			if err := copyDir(
				filepath.Join(modPath, e.Name()),
				filepath.Join(destDir, readmeAssertPath),
			); err != nil {
				return fmt.Errorf("copy docs: %w", err)
			}
			break
		}
	}

	return nil
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0755)
		}
		return copyFile(path, target)
	})
}
