package main

import (
	"fmt"
	"github.com/kohmebot/kohme/pkg/conf"
	"golang.org/x/mod/semver"
	"os"
	"os/exec"
	"os/signal"
	"path"
	"strings"
	"syscall"
	"time"
)

const template = `
// Code generated by plugin_gen; DO NOT EDIT.
package main

%s

func init()  {
	%s
}

`

const genPath = "./cmd/bot/plugin.gen.go"

func main() {

	pluginConf := conf.PluginConf{}

	err := pluginConf.ParseYamlFile(conf.PluginConfigPath)
	if os.IsNotExist(err) {
		_ = conf.CreatePluginConf()
		err = pluginConf.ParseYamlFile(conf.PluginConfigPath)
	}

	if err != nil {
		panic(err)
	}

	var recoverFile func()

	if b, ok := bak(); ok {
		recoverFile = func() {
			_ = writePlugin(b)
		}
	} else {
		recoverFile = func() {
			_ = os.Remove(genPath)
		}
	}

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sigs
		recoverFile()
		os.Exit(1)
	}()

	time.Sleep(500 * time.Millisecond)

	if err := gen(pluginConf.Plugins); err != nil {
		recoverFile()
		panic(err)
	}

}

func gen(plugins conf.PluginConfMap) error {
	var (
		importBuilder strings.Builder
		newBuilder    strings.Builder
		getUrl        []string
	)

	for name, c := range plugins {
		if len(c.Repo) <= 0 {
			c.Repo = fmt.Sprintf("github.com/kohmebot/%s", name)
		}
		name = path.Base(c.Repo)
		if name == "core" {
			continue
		}

		if semver.Compare(c.Version, "v2.0.0") >= 0 {
			// v2或以上版本
			major := semver.Major(c.Version)
			_, last := path.Split(c.Repo)
			if last != major {
				c.Repo = path.Join(c.Repo, major)
			}
		}
		importBuilder.WriteString(fmt.Sprintf(`import "%s"`, path.Join(c.Repo, name)))
		importBuilder.WriteByte('\n')
		newBuilder.WriteString(fmt.Sprintf("register(%s.NewPlugin)\n", name))

		if len(c.Version) <= 0 {
			getUrl = append(getUrl, fmt.Sprintf("%s@latest", c.Repo))
		} else {
			getUrl = append(getUrl, fmt.Sprintf("%s@%s", c.Repo, c.Version))
		}

	}

	p := fmt.Sprintf(template, importBuilder.String(), newBuilder.String())

	if err := writePlugin([]byte(p)); err != nil {
		return err
	}

	for _, u := range getUrl {
		if err := getMod(u); err != nil {
			return err
		}
	}

	return nil
}

func bak() ([]byte, bool) {
	if _, err := os.Stat(genPath); err != nil {
		return nil, false
	}

	b, err := os.ReadFile(genPath)
	if err != nil {
		return nil, false
	}

	return b, true

}

func writePlugin(b []byte) error {
	file, err := os.Create(genPath)
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = file.Write(b)
	return err
}

func getMod(url string) error {
	cmd := exec.Command("go", "get", url)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}
